services:
  ToolBox:
    image: toolbox
    build:
      context: ./ToolBox
      network: host
    restart: always
    volumes:
      - db-data:/app/db_data
      - promocodes:/app/promocodes
  AdminToolBox:
    image: admintb
    build:
      context: ./AdminToolBox
      network: host
    restart: always
    volumes:
      - db-data:/app/db_data
      - promocodes:/app/promocodes

volumes:
  db-data:
  promocodes: