services:
  toolbox:
    image: toolbox
    build:
      context: .
      network: host
    restart: always
    volumes:
      - ./:/apps
      - ./UsersData.db:/apps/UsersData.db
      - ./out.log:/apps/out.log