services:
  toolbox:
    image: toolbox
    build:
      context: .
      network: host
    restart: always
    volumes:
      - ./:/app
      - ./UsersData.db:/app/UsersData.db
      - ./out.log:/app/out.log